export { getAnalyticsDB, closeAnalyticsDB, useAnalyticsAccount } from "./connect";
export { accountKeyFor, currentAccountKey, ANONYMOUS_KEY } from "./accountDb";
export { enqueueAnalyticsWrite } from "./queue";
export {
  insertReadSession,
  getUnsyncedReadSessions,
  getAllReadSessions,
  getAllAudioSessions,
  getTopReadBanis,
  getRecentReadBanis,
  insertAudioSession,
  getUnsyncedAudioSessions,
  getTopListenedBanis,
  getRecentListenedBanis,
  upsertDailyActivity,
  setDailyActivity,
  getDayActivity,
  getAllDailyActivity,
  clearDailyActivity,
  getDayDetail,
  getDailyActivity,
  getQualifyingDates,
  getUnsyncedActivity,
  getActivityUpdatedSince,
  getOrCreateSummary,
  updateSummary,
  getReadingListeningTotals,
  getDailyActivityTotals,
  getYearActivityTotals,
  getAllTimeTotals,
  raiseAllTimeBaseline,
  markSynced,
  clearAllAnalyticsData,
  incrementBaniReadCount,
  getBaniReadCount,
  getAllBaniReadCounts,
  getCompletedBanisCount,
} from "./queries";
