export default {
  DB: "gutka_v01",
  ENGLISH: "ENGLISH",
  ENGLISH_TITLE_CASE: "English",
  HINDI: "HINDI",
  SHAHMUKHI: "SHAHMUKHI",
  IPA: "IPA",
  GURBANI_AKHAR_TRUE: "GurbaniAkharTrue",
  GURBANI_AKHAR_THICK_TRUE: "GurbaniAkharThickTrue",
  BALOO_PAAJI: "BalooPaaji2-Regular",
  BALOO_PAAJI_SEMI_BOLD: "BalooPaaji2-SemiBold",
  GURBANI_AKHAR_HEAVY_TRUE: "GurbaniAkharHeavyTrue",
  ANMOL_LIPI: "AnmolLipiSG",
  READER: "Reader",
  SETTINGS: "Settings",
  DASHBOARD: "Dashboard",
  SEVA: "Seva",
  // The current onboarding-carousel version. The carousel auto-opens whenever a
  // user's persisted `seenOnboardingVersion` is below this number, so every
  // build that bumps this re-shows the carousel exactly once to EVERYONE on
  // their next launch — fresh installs, updaters from old versions, and users
  // who already saw an earlier onboarding alike. Bump it whenever the
  // onboarding content should be force-shown again.
  ONBOARDING_VERSION: 1,
  EXTRA_SMALL: "EXTRA_SMALL",
  SMALL: "SMALL",
  MEDIUM: "MEDIUM",
  LARGE: "LARGE",
  EXTRA_LARGE: "EXTRA_LARGE",
  DEFAULT: "DEFAULT",
  HINDI_UNICODE: `हिंदी`,
  PUNJABI: `ਪੰਜਾਬੀ`,
  FRANCAIS: `Français`,
  ESPANOL: `Español`,
  ITALIANO: "Italiano",
  Default: "Default",
  SAT_SUBHAM_SAT: "SAT_SUBHAM_SAT",
  Light: "Light",
  Dark: "Dark",
  EXTRA_LONG: "EXTRA_LONG",
  LONG: "LONG",
  SHORT: "SHORT",
  EXISTS_BUDDHA_DAL: "existsBuddhaDal",
  EXISTS_TAKSAL: "existsTaksal",
  EXISTS_MEDIUM: "existsMedium",
  EXISTS_SGPS: "existsSGPC",
  GURMUKHI: "GURMUKHI",
  TRANSLITERATION: "TRANSLITERATION",
  TRANSLATION: "TRANSLATION",
  REMINDER_OPTIONS: "Reminder Options",
  KHALIS_FOUNDATION_URL: "https://khalisfoundation.org",
  BANI_DB_URL: "https://www.banidb.com/",
  sttm: "sttm",
  VISHRAAM_COLORED: "VISHRAAM_COLORED",
  VISHRAAM_GRADIENT: "VISHRAAM_GRADIENT",
  MAST_SABH_MAST: "MAST_SABH_MAST",
  DEFAULT_SPEED: 50,
  MARK_AS_READ: "mark-as-read",
  SOUND: "sound",
  REMINDERS_DEFAULT: "Reminders default",
  ALERT_DESCRIPTION: "Alert notification reminders for chosen Bani",
  WAHEGURU_SOUL: "waheguru_soul",
  REMINDERS_WAHEGURU_SOUL: "Reminders waheguru soul",
  WAKE_UP_JAP: "wake_up_jap",
  REMINDERS_WAKE_UP: "Reminders wake up jap",
  FOLDERSCREEN: "FolderScreen",
  HOME_SCREEN: "Home Screen",
  ABOUT_SCREEN: "About Screen",
  FALLBACK_SCREEN: "Fallback Screen",
  BOOKMARKS: "Bookmarks",
  FONT_SIZE: "fontSize",
  FONT_FACE: "fontFace",
  BANI_FONT_FACE: "baniFontFace",
  LANGUAGE: "appLanguage",
  TRANSLITERATION_LANGUAGE: "transliterationLanguage",
  SPANISH: "spanish",
  NIGHT_MODE: "nightMode",
  KEEP_AWAKE: "keepAwake",
  BANI_LENGTH: "baniLength",
  THEME: "Theme",
  LARIVAAR: "larivaar",
  LARIVAAR_ASSIST: "larivaarAssist",
  PADCHED: "padched",
  STATISTICS: "statistics",
  STATUS_BAR: "statusBar",
  PARAGRAPH: "paragraph",
  AUTO_SCROLL: "autoScroll",
  AUDIO: "audio",
  AUDIO_AUTO_PLAY: "audioAutoPlay",
  AUDIO_SYNC_SCROLL: "audioSyncScroll",
  DEFAULT_AUDIO: "defaultAudio",
  VISHRAAM: "vishraam",
  VISHRAAM_OPTION: "vishraamOption",
  VISHRAAM_SOURCE: "vishraamSource",
  REMINDERS: "reminders",
  REMINDER_SOUND: "reminderSound",
  EDIT_BANI_ORDER: "Edit Bani Order",
  ADD_REMINDER: "addReminder",
  RESET_REMINDER: "resetReminderDefault",
  UPDATE_REMINDER: "updateReminder",
  PORTRAIT: "PORTRAIT",
  LANDSCAPE: "LANDSCAPE",
  REMOTE_DB_URL: "https://banidb.blob.core.windows.net/database",
  BASIC_AUTH_USERNAME: "admin",
  BASIC_AUTH_PASSWORD: "",
  REMOTE_AUDIO_API_URL:
    "https://sttm-audio-api-v2.salmonriver-80392db4.eastus.azurecontainerapps.io/v1",
  // Single source of truth for the audio/lyrics asset host. Points at the Azure
  // Front Door CDN (origin = banidb.blob.core.windows.net/audios). Swapping this
  // host is safe for existing users: downloaded-track matching and bundled-lyrics
  // lookups are keyed on the artist/file PATH, not the full URL.
  AUDIO_BASE_URL: "https://gurbani-audios-c4abhzghhnccd5gj.z01.azurefd.net/audios",
  CHOPAYI_SAHIB_ID: 9,
  REHRAAS_SAHIB_ID: 21,
  BANI_IDS_WITH_LENGTH_VARIANTS: [9, 21, 23],
  MAST_SABH_MAST_TUKK: "smwpq msqu suB msqu",
  MAST_SABH_MAST_TUKK_UNI: "ਸਮਾਪਤ ਮਸਤੁ ਸੁਭ ਮਸਤੁ",
  MINIMUM_BOTTOM_PADDING: 35,
  defaultBani: {
    id: 1,
    title: "gur mMqR",
    titleUni: "ਗੁਰ ਮੰਤ੍ਰ",
  },
  ICON_SIZE_SMALL: 18,
  ANALYTICS_DB_NAME: "analytics_v01.db",
  MIN_READ_SESSION_SECONDS: 240,
  MIN_LISTEN_SESSION_SECONDS: 240,
  KHALIS_APPS_API_URL: "",
  ANALYTICS_SYNC_API_URL: "",

  // ─── Dashboard redesign ───────────────────────────────────────────────────
  // Section keys for the customizable dashboard layout (order below = default order).
  DASHBOARD_SECTIONS: {
    STREAK: "streak",
    NITNEM: "nitnem",
    EXPLORE: "explore",
    PRACTICE: "practice",
    CALENDAR: "calendar",
    WEEK_CHART: "weekChart",
    DISCOVER: "discover",
    REMINDERS: "reminders",
    RANDOM_SHABAD: "randomShabad",
    VAAK: "vaak",
  },
  // Minimum number of visible sections the user must keep when customizing layout.
  DASHBOARD_MIN_VISIBLE: 4,
  // Default daily Nitnem bani set (classic Sat Bania by Banis.ID).
  DEFAULT_NITNEM_BANI_IDS: [2, 3, 4, 9, 5, 21, 1],

  // Dashboard backend.
  // Dev only: the device reaches the Mac's local server via `adb reverse tcp:3500 tcp:3500`.
  // Release builds use "" → direct sources (Daily Vaak → BaniDB, Word of Day → local).
  // When the backend is deployed, replace "" with the production HTTPS base/URLs.
  DASHBOARD_API_BASE_URL: __DEV__ ? "http://localhost:3500" : "",
  // Random Shabad stays on BaniDB directly (backend proxy was dropped).
  RANDOM_SHABAD_API_URL: "",
  DAILY_VAAK_API_URL: __DEV__ ? "http://localhost:3500/dashboard/daily-vaak" : "",
  WORD_OF_DAY_API_URL: __DEV__ ? "http://localhost:3500/dashboard/word-of-day" : "",
  UPCOMING_EVENTS_API_URL: "",
  NANAKSHAHI_API_URL: "",
};
