import * as actions from "./actions";
import colors from "./colors";
import {
  FallBack,
  BaniLengthSelector,
  LanguageSelector,
  Coachmark,
  HOME_STEPS,
  PREVIEW_STEPS,
  PLAYER_STEPS,
  DOWNLOADS_STEPS,
  SETTINGS_MANAGE_STEPS,
  CoachmarkHost,
  AudioHintCallout,
  ExplorePromptCallout,
  DownloadsGuideCallout,
  BaniList,
  CustomText,
  GradientDivider,
  useCustomScrollbar,
  ListItemTitle,
  BottomNavigation,
  SafeArea,
  StatusBarComponent,
  ThemedSwitch,
  ConfirmDialogHost,
  showConfirm,
} from "./components";
import { COACH } from "./onboarding/coachmarkKeys";
import useCoachmark from "./onboarding/useCoachmark";
import orderedBani from "./components/BaniList/baniOrderHelper";
import constant from "./constant";
import useTheme, { useNetwork } from "./context";
import defaultBaniOrder from "./defaultBaniOrder";
import {
  allowTracking,
  trackReaderEvent,
  trackSettingEvent,
  trackReminderEvent,
  trackAudioEvent,
  trackSevaEvent,
  trackBaniOpen,
  trackBaniListen,
  trackBaniListenCompletion,
  trackBaniArtistDefault,
  trackTrackDownload,
  trackAudioLinkRequest,
  trackScrollProgress,
  trackTourEvent,
} from "./firebase/analytics";
import { logError, initializeCrashlytics, setCustomKey, logMessage } from "./firebase/crashlytics";
import baseFontSize, { validateBaniOrder } from "./helpers";
import { openInAppBrowser } from "./inAppBrowser";
import useKeepAwake from "./hooks/keepAwake";
import useBackHandler from "./hooks/useBackHandler";
import useThemedStyles from "./hooks/useThemedStyles";
import STRINGS from "./localization";
import {
  updateReminders,
  cancelAllReminders,
  checkPermissions,
  requestNotificationPermission,
  resetBadgeCount,
} from "./notifications";
import {
  ensureDbExists,
  checkForBaniDBUpdate,
  REMOTE_DB_URL,
  writeRemoteMD5Hash,
  LOCAL_DB_PATH,
  listDocumentDirectory,
  revertMD5Hash,
  getCurrentDBMD5Hash,
} from "./rnfs";
import { navigate, navigateTo, navigationRef } from "./rootNavigation";
import createStore from "./store";
import { showToast, showErrorToast, showSuccessToast, showInfoToast } from "./toast";
import convertToUnicode from "./utils";

export {
  colors,
  constant,
  actions,
  STRINGS,
  logError,
  logMessage,
  initializeCrashlytics,
  allowTracking,
  trackReaderEvent,
  trackAudioEvent,
  trackSevaEvent,
  trackReminderEvent,
  trackSettingEvent,
  updateReminders,
  checkPermissions,
  requestNotificationPermission,
  cancelAllReminders,
  FallBack,
  BaniLengthSelector,
  LanguageSelector,
  Coachmark,
  HOME_STEPS,
  PREVIEW_STEPS,
  PLAYER_STEPS,
  DOWNLOADS_STEPS,
  SETTINGS_MANAGE_STEPS,
  CoachmarkHost,
  AudioHintCallout,
  ExplorePromptCallout,
  DownloadsGuideCallout,
  COACH,
  useCoachmark,
  useKeepAwake,
  BaniList,
  CustomText,
  GradientDivider,
  ConfirmDialogHost,
  showConfirm,
  trackTourEvent,
  useCustomScrollbar,
  baseFontSize,
  resetBadgeCount,
  createStore,
  orderedBani,
  setCustomKey,
  navigateTo,
  navigate,
  navigationRef,
  defaultBaniOrder,
  validateBaniOrder,
  ensureDbExists,
  checkForBaniDBUpdate,
  REMOTE_DB_URL,
  writeRemoteMD5Hash,
  LOCAL_DB_PATH,
  listDocumentDirectory,
  revertMD5Hash,
  getCurrentDBMD5Hash,
  StatusBarComponent,
  SafeArea,
  showToast,
  showErrorToast,
  showSuccessToast,
  showInfoToast,
  convertToUnicode,
  BottomNavigation,
  useTheme,
  useNetwork,
  useThemedStyles,
  ListItemTitle,
  useBackHandler,
  openInAppBrowser,
  trackBaniOpen,
  trackBaniListen,
  trackBaniListenCompletion,
  trackBaniArtistDefault,
  trackTrackDownload,
  trackAudioLinkRequest,
  trackScrollProgress,
  ThemedSwitch,
};
