import * as actions from "./actions";
import {
  FallBack,
  BaniLengthSelector,
  OnboardingCarousel,
  BaniList,
  CustomText,
  GradientDivider,
  useCustomScrollbar,
  ListItemTitle,
  BottomNavigation,
  SafeArea,
  StatusBarComponent,
  ThemedSwitch,
  ConfirmDialogHost,
  showConfirm,
} from "./components";
import orderedBani from "./components/BaniList/baniOrderHelper";
import constant from "./constant";
import useTheme, { useNetwork } from "./context";
import defaultBaniOrder from "./defaultBaniOrder";
import {
  allowTracking,
  trackReaderEvent,
  trackSettingEvent,
  trackReminderEvent,
  trackAudioEvent,
  trackSevaEvent,
  trackPothiEvent,
  trackBaniOpen,
  trackBaniListen,
  trackBaniListenCompletion,
  trackBaniArtistDefault,
  trackTrackDownload,
  trackAudioLinkRequest,
  trackScrollProgress,
  trackNavBar,
  trackPlayerForm,
  trackTourEvent,
  trackJourneyView,
  trackKhalisAppClicked,
  trackBaniCompleted,
  trackAudioStarted,
  trackAudioCompleted,
} from "./firebase/analytics";
import { logError, initializeCrashlytics, setCustomKey, logMessage } from "./firebase/crashlytics";
import {
  initializePerformanceMonitoring,
  startPerformanceTrace,
  stopTrace,
  resetTrace,
} from "./firebase/performance";
import baseFontSize, { validateBaniOrder } from "./helpers";
import useKeepAwake from "./hooks/keepAwake";
import useBackHandler from "./hooks/useBackHandler";
import useThemedStyles from "./hooks/useThemedStyles";
import { openInAppBrowser } from "./inAppBrowser";
import STRINGS from "./localization";
import {
  updateReminders,
  cancelAllReminders,
  checkPermissions,
  canScheduleExactAlarms,
  openExactAlarmSettings,
  openNotificationSettings,
  hasNotificationPermission,
  requestNotificationPermission,
  resetBadgeCount,
} from "./notifications";
import {
  ensureDbExists,
  checkForBaniDBUpdate,
  REMOTE_DB_URL,
  writeRemoteMD5Hash,
  LOCAL_DB_PATH,
  listDocumentDirectory,
  revertMD5Hash,
  getCurrentDBMD5Hash,
} from "./rnfs";
import { navigate, navigateTo, navigationRef } from "./rootNavigation";
import scheduleReminders from "./scheduleReminders";
import { startLogin as ssoLogin, startLogout as ssoLogout } from "./sso/khalisSso";
import { readToken as readSsoToken } from "./sso/tokenStore";
import createStore from "./store";
import {
  showToast,
  showErrorToast,
  showSuccessToast,
  showInfoToast,
  setToastBottomReservation,
} from "./toast";
import convertToUnicode from "./utils";

export {

  constant,
  actions,
  STRINGS,
  logError,
  logMessage,
  initializeCrashlytics,
  initializePerformanceMonitoring,
  startPerformanceTrace,
  stopTrace,
  resetTrace,
  allowTracking,
  trackReaderEvent,
  trackAudioEvent,
  trackSevaEvent,
  trackPothiEvent,
  trackReminderEvent,
  trackSettingEvent,
  updateReminders,
  scheduleReminders,
  canScheduleExactAlarms,
  openExactAlarmSettings,
  openNotificationSettings,
  hasNotificationPermission,
  checkPermissions,
  requestNotificationPermission,
  cancelAllReminders,
  FallBack,
  BaniLengthSelector,
  OnboardingCarousel,
  useKeepAwake,
  BaniList,
  CustomText,
  GradientDivider,
  ConfirmDialogHost,
  showConfirm,
  trackTourEvent,
  useCustomScrollbar,
  baseFontSize,
  resetBadgeCount,
  createStore,
  orderedBani,
  setCustomKey,
  navigateTo,
  navigate,
  navigationRef,
  defaultBaniOrder,
  validateBaniOrder,
  ensureDbExists,
  checkForBaniDBUpdate,
  REMOTE_DB_URL,
  writeRemoteMD5Hash,
  LOCAL_DB_PATH,
  listDocumentDirectory,
  revertMD5Hash,
  getCurrentDBMD5Hash,
  StatusBarComponent,
  SafeArea,
  showToast,
  showErrorToast,
  showSuccessToast,
  showInfoToast,
  setToastBottomReservation,
  convertToUnicode,
  BottomNavigation,
  useTheme,
  useNetwork,
  useThemedStyles,
  ListItemTitle,
  useBackHandler,
  openInAppBrowser,
  ssoLogin,
  ssoLogout,
  readSsoToken,
  trackBaniOpen,
  trackBaniListen,
  trackBaniListenCompletion,
  trackBaniArtistDefault,
  trackTrackDownload,
  trackAudioLinkRequest,
  trackScrollProgress,
  trackNavBar,
  trackPlayerForm,
  trackJourneyView,
  trackKhalisAppClicked,
  trackBaniCompleted,
  trackAudioStarted,
  trackAudioCompleted,
  ThemedSwitch,
};
